chore: Update dev_deploy.yml, install zrok if not installed

diff --git a/.github/workflows/dev_deploy.yml b/.github/workflows/dev_deploy.yml
--- a/.github/workflows/dev_deploy.yml
+++ b/.github/workflows/dev_deploy.yml
@@ -29,28 +29,33 @@ jobs:
 
       - name: Install zrok
         run: |
-          cd $(mktemp -d)
-          
-          # Get latest ZROK version
-          ZROK_VERSION=$(
-            curl -sSf https://api.github.com/repos/openziti/zrok/releases/latest \
-            | jq -r '.tag_name'
-          )
+          if ! command -v zrok &> /dev/null; then
+            echo "zrok not found, proceeding with installation."
+            cd $(mktemp -d)
+            
+            # Get latest ZROK version
+            ZROK_VERSION=$(
+              curl -sSf https://api.github.com/repos/openziti/zrok/releases/latest \
+              | jq -r '.tag_name'
+            )
 
-          # Determine architecture
-          case $(uname -m) in
-            x86_64)         GOXARCH=amd64 ;;
-            aarch64|arm64)  GOXARCH=arm64 ;;
-            arm*)           GOXARCH=armv7 ;;
-            *)              echo "ERROR: unknown arch '$(uname -m)'" >&2; exit 1 ;;
-          esac
+            # Determine architecture
+            case $(uname -m) in
+              x86_64)         GOXARCH=amd64 ;;
+              aarch64|arm64)  GOXARCH=arm64 ;;
+              arm*)           GOXARCH=armv7 ;;
+              *)              echo "ERROR: unknown arch '$(uname -m)'" >&2; exit 1 ;;
+            esac
 
-          # Download and install zrok
-          curl -sSfL \
-            "https://github.com/openziti/zrok/releases/download/${ZROK_VERSION}/zrok_${ZROK_VERSION#v}_linux_${GOXARCH}.tar.gz" \
-            | tar -xz -f -
+            # Download and install zrok
+            curl -sSfL \
+              "https://github.com/openziti/zrok/releases/download/${ZROK_VERSION}/zrok_${ZROK_VERSION#v}_linux_${GOXARCH}.tar.gz" \
+              | tar -xz -f -
 
-          sudo install -o root -g root ./zrok /usr/local/bin/
+            sudo install -o root -g root ./zrok /usr/local/bin/
+          else
+            echo "zrok is already installed, skipping installation."
+          fi
 
       - name: Verify zrok installation
         run: zrok version ${{ secrets.ZROK_TOKEN }}
